package handlers

import "github.com/gofiber/fiber/v2"

type LegalHandler struct{}

func NewLegalHandler() *LegalHandler {
	return &LegalHandler{}
}

func (h *LegalHandler) PrivacyPolicy(c *fiber.Ctx) error {
	html := `<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Privacy Policy - EcoMonitor AI</title><style>body{font-family:-apple-system,system-ui,sans-serif;max-width:800px;margin:0 auto;padding:20px;color:#333;line-height:1.6}h1{color:#10B981}h2{color:#059669;margin-top:30px}</style></head><body><h1>Privacy Policy</h1><p><strong>Last updated:</strong> February 7, 2026</p><p>EcoMonitor AI ("we", "our", or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and safeguard your information.</p><h2>Information We Collect</h2><ul><li><strong>Account Information:</strong> Email address and encrypted password when you create an account.</li><li><strong>Location Data:</strong> GPS coordinates you manually save to track environmental changes.</li><li><strong>Usage Data:</strong> App interaction data to improve our services.</li></ul><h2>How We Use Your Information</h2><ul><li>To provide and maintain our service</li><li>To process environmental monitoring requests</li><li>To send you alerts about environmental changes</li><li>To improve our app experience</li></ul><h2>Data Storage & Security</h2><p>Your data is stored securely on encrypted servers. We use industry-standard security measures including JWT authentication and encrypted connections.</p><h2>Third-Party Services</h2><ul><li><strong>RevenueCat:</strong> For subscription management. See their <a href="https://www.revenuecat.com/privacy">privacy policy</a>.</li><li><strong>Apple Sign In:</strong> We receive only your email and name from Apple.</li></ul><h2>Data Deletion</h2><p>You can delete your account and all associated data at any time from the Settings screen in the app, or by contacting us.</p><h2>Children's Privacy</h2><p>Our app is not intended for children under 13. We do not knowingly collect data from children.</p><h2>Changes to This Policy</h2><p>We may update this policy from time to time. We will notify you of any changes by posting the new policy in the app.</p><h2>Contact Us</h2><p>If you have questions about this Privacy Policy, contact us at: <strong>ahmetk3436@gmail.com</strong></p></body></html>`
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(html)
}

func (h *LegalHandler) TermsOfService(c *fiber.Ctx) error {
	html := `<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Terms of Service - EcoMonitor AI</title><style>body{font-family:-apple-system,system-ui,sans-serif;max-width:800px;margin:0 auto;padding:20px;color:#333;line-height:1.6}h1{color:#10B981}h2{color:#059669;margin-top:30px}</style></head><body><h1>Terms of Service</h1><p><strong>Last updated:</strong> February 7, 2026</p><p>By using EcoMonitor AI, you agree to these Terms of Service.</p><h2>Use of Service</h2><p>EcoMonitor AI provides environmental monitoring and satellite change detection tools. You must be at least 13 years old to use this app.</p><h2>Account Responsibilities</h2><ul><li>You are responsible for maintaining the security of your account.</li><li>You must provide accurate information when creating an account.</li><li>You must not use the service for any illegal purposes.</li></ul><h2>Subscriptions</h2><ul><li>Premium features require a paid subscription.</li><li>Subscriptions are billed through Apple's App Store.</li><li>You can cancel your subscription at any time through your Apple ID settings.</li><li>Refunds are handled by Apple according to their refund policy.</li></ul><h2>Content Guidelines</h2><ul><li>You must not post offensive, harmful, or illegal content.</li><li>We reserve the right to remove content that violates our guidelines.</li><li>You retain ownership of content you create.</li></ul><h2>Limitation of Liability</h2><p>EcoMonitor AI is provided "as is" without warranties. We are not liable for any damages arising from your use of the app. Environmental data is for informational purposes only.</p><h2>Termination</h2><p>We may terminate your account if you violate these terms. You can delete your account at any time.</p><h2>Contact</h2><p>For questions about these Terms, contact us at: <strong>ahmetk3436@gmail.com</strong></p></body></html>`
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(html)
}
